CONTRIBUTING.md
README.md

fixing readme and contrib

---

charts/load-test-grpc/Chart.yaml
charts/load-test-http/Chart.yaml

Part of https://github.com/iter8-tools/iter8/issues/1174

set chart version to 0.9.0

---

CONTRIBUTING.md
README.md

Readme.md and contributing.md <same as iter8 and docs repo>

---

CONTRIBUTING.md

add action to CONTRIBUTING.md

---

charts/iter8/Chart.yaml

fixing dependency

---

charts/iter8lib/Chart.yaml
charts/iter8lib/templates/_task-github.tpl
charts/iter8lib/templates/_task-slack.tpl
templates/_payload-github.tpl
templates/_payload-slack.tpl

Add notify templates

---

charts/autox/Chart.yaml
charts/autox/templates/deployment.yaml
charts/autox/templates/roles.yaml

Small addition to autoX

---

charts/abn-service/Chart.yaml
charts/abn-service/values.yaml

fix default version

---

charts/litmuschaos/Chart.yaml
charts/litmuschaos/templates/_chaosengine.tpl
charts/litmuschaos/templates/_chaosexperiment.tpl
charts/litmuschaos/templates/_rbac.tpl
charts/litmuschaos/values.yaml

Fixing the rbac issues

---

charts/litmuschaos/Chart.yaml
charts/litmuschaos/templates/_chaosengine.tpl

fix chaos engine template

---

charts/litmuschaos/Chart.yaml
charts/litmuschaos/templates/_chaosengine.tpl
charts/litmuschaos/templates/_chaosexperiment.tpl
charts/litmuschaos/values.yaml

pod-delete experiment

---

charts/iter8/Chart.yaml
charts/iter8/templates/_payload-slack.tpl

fix _payload-slack.tpl

---

charts/iter8/Chart.yaml
charts/iter8/values.yaml

default in chart needed update

0.11 -> 0.12

---

README.md

fix test badge

---

.github/workflows/releasecharts.yaml
config.yaml

updated config

---

.github/workflows/releasecharts.yaml
config.yaml

reverting part of the config

---

charts/abn/Chart.yaml
charts/abn/templates/configmap.yaml
charts/abn/templates/roles.yaml
charts/abn/templates/secret.yaml
charts/abn/values.yaml

change keyword from applications to apps

shorten applications

---

charts/iter8/Chart.yaml
charts/iter8/templates/_k-role.tpl
charts/iter8/templates/_task-ready.tpl

Updates to iter8 chart to support kserve inferenceservices

support kserve isvc

---

.github/workflows/releasecharts.yaml

update workflow actions

---

templates/custommetrics/istio-prom.tpl

Partially addresses https://github.com/iter8-tools/iter8/issues/1399

fix istio-prom.tpl

---

templates/custommetrics/istio-prom.tpl

Part of fix for  https://github.com/iter8-tools/iter8/issues/1407

add tonumber to error-rate

---

charts/iter8/Chart.yaml
charts/iter8/templates/_task-grpc.tpl
charts/iter8/templates/_task-http.tpl
templates/custommetrics/istio-prom.tpl

Chart changes for https://github.com/iter8-tools/iter8/issues/1406
Also fixes template for https://github.com/iter8-tools/iter8/issues/1412

add warmup tasks to chart

---

charts/traffic/Chart.yaml
charts/traffic/templates/roles.yaml

Add RBAC for pods

---

.github/workflows/test.yaml
charts/iter8/Chart.yaml
charts/iter8/templates/_k-cronjob.tpl
charts/iter8/templates/_k-job.tpl

Partially addresses iter8-tools/iter8#1447

Add workflows

---

kustomize/traffic/clusterScoped/clusterroles.yaml
kustomize/traffic/namespaceScoped/roles.yaml

Fixes https://github.com/iter8-tools/iter8/issues/1454

fix kustomize problems

---

charts/traffic-templates/Chart.yaml
charts/traffic-templates/templates/_routemap-mirror.tpl

Mirror template should check for 0 weight for mirror and not attempt to configure mirroring in this case.

fix mirror template
